### ISSUE TITLE
Target different elements for hiding

### ISSUE THREAD

**Issue by trdischat** [kandashi/Hidden-Soundtracks#1]
I love your approach to hiding the playlist contents from the players.  Very elegant to do the whole things with CSS.  The current version, however, still reveals the name of the playlist of the currently playing track, and it wipes out the labels for the volume sliders in the Global Volume Controls.  I tinkered with your approach and settled on this CSS code:
```css
:root {
  --myDisplay: block;
}

#playlists .directory-header,
#playlists #currently-playing,
#playlists .directory-list {
  display: var(--myDisplay);
}
```
This blocks the display of everything on the Playlist sidebar, with the exception of the Global Volume Controls.

![GVC](https://user-images.githubusercontent.com/52774325/121120414-58b13480-c7d2-11eb-9742-eff271f2cacb.png)
